apiVersion: v1
kind: Secret
metadata:
  name: {{ include "djtip.fullname" . }}-secrets
  labels:
    {{- include "djtip.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: djtip-secrets
  labels:
    {{- include "djtip.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}