AllCops:
  NewCops: enable
  Exclude:
    - 'mongodb-data/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
