# Traefik Ingress Controller Configuration

# Configure the traefik subchart
traefik:
  fullnameOverride: "traefik"

  service:
    type: NodePort
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9100"
    additionalPorts:
      - name: metrics
        containerPort: 9100
        protocol: TCP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  metrics:
    prometheus:
      addEntryPointsLabels: true
      addServicesLabels: true
      addRoutersLabels: true
      entryPoint: metrics

  providers:
    kubernetesIngress:
      enabled: true
      publishedService:
        enabled: true
