# Development environment overrides
# Inherits from values.yaml

# Development-specific ingress
ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging-dns01"
  hosts:
    - host: app.dev.djtip.jennings.au
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: djtip-tls
      hosts:
        - app.dev.djtip.jennings.au

# Development uses default env values from values.yaml
# No environment variable overrides needed
