apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rob-j-au/djtip.git
    targetRevision: main
    path: .cicd/helm/observability
    helm:
      releaseName: obs
      valueFiles:
        - values.yaml
      parameters:
        - name: kube-prometheus-stack.grafana.ingress.hosts[0]
          value: "grafana.k8s.pi.jennings.au"
        - name: kube-prometheus-stack.grafana.grafana\.ini.server.root_url
          value: "https://grafana.k8s.pi.jennings.au"

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true  # Required for CRDs

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
