development:
  clients:
    default:
      database: djtip_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: djtip_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/djtip_production' %>
      options:
        server_selection_timeout: 5
