apiVersion: v2
name: haproxy-ingress
description: HAProxy Ingress Controller for Kubernetes
type: application
version: 0.1.0
appVersion: "3.2.6"

dependencies:
  - name: kubernetes-ingress
    version: "1.49.0"
    repository: https://haproxytech.github.io/helm-charts
